#!/bin/bash
#
# Perform necessary kramdown-rfc2629 setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

echo "Thank you for installing kramdown-rfc2629!"

exit 0
